### PR TITLE
V1.0 release

### PR DESCRIPTION
**Pull request by bl-young**
Major updates for v1.0.0 release:
-generated methods stored in local user directory (via esupy)
-addition of ImpactWorld+ (requires FEDEFL v1.0.7)
-new functions enable the generation of custom endpoint methods, e.g. valuation methods; example data/script provided for Weidema 2009
-documentation for JOSS

### CODE REVIEW

**Review by WesIngwersen — COMMENTED** [review]
I'm getting an error trying to run the valuation method
https://github.com/USEPA/LCIAformatter/blob/v1.0_release/examples/valuation.py
see my post in  JIRA  LCIAF-39

**Comment by WesIngwersen** [comment]
Some unit tests are failing

In `test_remove_norels`
```
AssertionError: 'air/unspecified' != 'air'
- air/unspecified
+ air


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "C:\Users\wesle\LCIAformatter\tests\test_fmap.py", line 11, in test_remove_norels
    norm("Elementary flows / Emission to air / unspecified"), "air")
```

In `test_duplicate_flows`
```
AssertionError: False is not true : Duplicate factors in one or more methods
```

**Comment by bl-young** [comment]
@WesIngwersen the issues above and on jira tasks have been addressed

**Comment by WesIngwersen** [comment]
still getting an error trying to run valuation.py
```
2021-03-19 10:45:55 INFO     developing endpoint methods...
2021-03-19 10:45:57 INFO     loaded ReCiPe_2016 from C:\Users\wesle\AppData\Local\lciafmt/recipe_2016
2021-03-19 10:45:57 ERROR    specified method not found
Traceback (most recent call last):
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\range.py", line 355, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range
```
i'm available to meet in about 10-15 mins if we need to troubleshoot

**Comment by bl-young** [comment]
@WesIngwersen I believe a carry-over bug from before. You still have a recipe method in your local directory, its just not a complete recipe method. This won't happen in the future as only complete methods should be stored.
Delete the current ReCiPe method and it should re-create it. Sorry about that.

**Review by WesIngwersen — APPROVED** [review]
valuation.py fixed
test_fmap.py passes all tests
test_mapped_method passes all tests

**Comment by WesIngwersen** [comment]
i will merge but not yet ready for the v1 prerelease to be minted..we can work on minor updates like requirements in master

**Pull request merged**
