### PR TITLE
Update to incorporate esupy

### PR DESCRIPTION
**Pull request by bl-young**
Drafting this pull request to review integration of esupy
-saves parquet and json in local directory
-subdirectories specified by method in lciafmt/data/methods.json using paramter "path"

### CODE REVIEW

**Comment by bl-young** [comment]
@WesIngwersen @catherinebirney @Andrew809 hoping some of you might be able to test it out on your machines

**Comment by catherinebirney** [comment]
@bl-young I get an error message for the requirements/setup that v1.0.6 of fedelemflowlist does not exist. Checking fedelemflowlist gihub repo, the current version is v1.0.5

**Comment by bl-young** [comment]
Thanks - sorry had forgot to release that version. No new flows, just new mappings. Should be good now.

**Comment by catherinebirney** [comment]
@bl-young I am able to run the three example .py scripts (although a number of recipe.py and traci.py readouts say 'DEBUG could not map flow..."). The outputs from those scripts are saved in my local directory for lciafmt, so success.

**Comment by bl-young** [comment]
Yes there are a lot of unmapped flows, this is not an error. I think in a different branch I have updated the logger to be INFO by default. Thanks for checking!

**Comment by WesIngwersen** [comment]
It does not fail for me, but I didn't note any difference in behavior after running the second time, in other words after parquets were stored I don't see that it was loading them versus regenerating it

**Comment by bl-young** [comment]
@WesIngwersen - yes the way it is currently set up, but which can easily be altered:
-Running the example scripts generates the methods from the source and includes the function to store as parquet.
-With the function [get_mapped_method](https://github.com/USEPA/LCIAformatter/blob/refac_data_storage/lciafmt/__init__.py#L102), a user can access a mapped method. If one exists in the local directory, it will access that one first, if not it will generate it. But at this point the method doesn't get stored through this function. This would be very easy to add if we want it to be included there as well.

**Pull request merged**
